name: Deploy Slidev Presentations

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [main] # Or your primary branch name

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages # Group by 'pages' to cancel in-progress runs on new commits
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # Use the latest Long-Term Support Node.js version
          # ni will choose the package manager based on your lock file (pnpm-lock.yaml or package-lock.json)
          # If you have both, ensure 'ni' picks the one you intend to use for caching.
          # For explicit pnpm caching if pnpm is used by 'ni':
          # cache: 'pnpm'
          # For explicit npm caching if npm is used by 'ni':
          cache: "npm"

      - name: Setup @antfu/ni # Installs ni for unified package manager commands
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci # Clean install: uses npm ci, pnpm install --frozen-lockfile, or yarn install --frozen-lockfile

      - name: Prepare dist directory
        run: mkdir -p dist # Create the root dist directory where all built files will go

      - name: Make scripts executable
        run: |
          chmod +x ./.github/scripts/build-root-presentation.sh
          chmod +x ./.github/scripts/build-subdirectory-presentations.sh

      # --- Build Root Presentation ---
      # Builds slides.md from the root of your repository
      - name: Build Root Presentation (if slides.md exists at root)
        env:
          GH_PAGES_REPO_NAME: ${{ github.event.repository.name }}
        run: bash ./.github/scripts/build-root-presentation.sh

      # --- Build Presentations from Subdirectories ---
      # Discovers and builds presentations in the 'presentations' directory
      - name: Discover and Build Presentations from Subdirectories
        env:
          GH_PAGES_REPO_NAME: ${{ github.event.repository.name }}
        run: bash ./.github/scripts/build-subdirectory-presentations.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Upload the entire dist folder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # This job depends on the 'build' job completing successfully
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
